### ISSUE TITLE
tls.cpp  104 行，  static char* get_server_extension_name(const char* data, uint32_t datalen) 函数中存在逻辑错误

### ISSUE THREAD

**Issue by 11235yuan** [MiChuancey/Protocol_Restoration#2]
pos += 3 + len;     // pos + 3 指向 server name , 再加 len 跳过了本包的所有扩展字段

应该是 pos += 3 + server_name_len；

最内层循环的 while (pos + 3 < extension_end) {...} 应当是为了循环处理 Server Name list 中的 所有 Server Name,

其 pos 应当指向每一个 Server Name 项的第一个字段（Server Name Type），循环才能正确执行。

因此，只需要跳过 当前扩展字段 当中的，当前这个Server Name 项的  Server Name Type、Server Name length、Server Name,

转而处理 当前扩展字段 当中 Server Name list 中的其他 Server Name 项。 

奇怪的地方是，如果找到一个合法的 Server Name，函数调用就退出了，

而写成 pos += 3 + len； 其目的是不是要在没有找到合法的Server Name就直接退函数调用？

那如果是这个目的，哪两层循环的意义何在？

**Comment by CChuancey** [comment]
首先说明第一次循环的作用：函数`static char* get_server_extension_name(const char* data, uint32_t datalen) ` 的作用是从整个Client Hello中寻找SNI，因此65行之前的内容存在的意义都是为了跳过报文中Extensions前面的内容，66-69行的意义是获取Extensions的长度，接下来需要该长度来遍历所有的Extensions去寻找`Type`为`server_name`的Extension(77行)，第一层循环的作用就是这样。
接下来说明为什么二层循环寻找到一个`Server Name`就退出的原因：首先本项目针对TLS1.2，在TLS1.2以前的版本中，`Server Name List`中允许存在多个相同的`Server Name Type`，此时的`Server Name List`中会存在多个`Server Name`。但是从TLS1.2开始，每个`Server Name List`中不允许存在相同的`Server Name Type`，而TLS1.2中的`Server Name Type`中只有`host_name`这一种类型，因此TLS1.2中`Server Name List`只会出现一个`Server Name`，所以找到之后就可以退出函数了。
RFC原话：
>  Note: Earlier versions of this specification permitted multiple names of the same name_type.  In practice, current client       implementations only send one name, and the client cannot necessarily find out which name the server selected.  Multiple       names of the same name_type are therefore now prohibited.

**Comment by CChuancey** [comment]
> pos += 3 + len; // pos + 3 指向 server name , 再加 len 跳过了本包的所有扩展字段
> 
> 应该是 pos += 3 + server_name_len；
> 
> 最内层循环的 while (pos + 3 < extension_end) {...} 应当是为了循环处理 Server Name list 中的 所有 Server Name,
> 
> 其 pos 应当指向每一个 Server Name 项的第一个字段（Server Name Type），循环才能正确执行。
> 
> 因此，只需要跳过 当前扩展字段 当中的，当前这个Server Name 项的 Server Name Type、Server Name length、Server Name,
> 
> 转而处理 当前扩展字段 当中 Server Name list 中的其他 Server Name 项。
> 
> 奇怪的地方是，如果找到一个合法的 Server Name，函数调用就退出了，
> 
> 而写成 pos += 3 + len； 其目的是不是要在没有找到合法的Server Name就直接退函数调用？
> 
> 那如果是这个目的，哪两层循环的意义何在？

首先说明第一次循环的作用：函数`static char* get_server_extension_name(const char* data, uint32_t datalen) ` 的作用是从整个Client Hello中寻找SNI，因此65行之前的内容存在的意义都是为了跳过报文中Extensions前面的内容，66-69行的意义是获取Extensions的长度，接下来需要该长度来遍历所有的Extensions去寻找`Type`为`server_name`的Extension(77行)，第一层循环的作用就是这样。
接下来说明为什么二层循环寻找到一个`Server Name`就退出的原因：首先本项目针对TLS1.2，在TLS1.2以前的版本中，`Server Name List`中允许存在多个相同的`Server Name Type`，此时的`Server Name List`中会存在多个`Server Name`。但是从TLS1.2开始，每个`Server Name List`中不允许存在相同的`Server Name Type`，而TLS1.2中的`Server Name Type`中只有`host_name`这一种类型，因此TLS1.2中`Server Name List`只会出现一个`Server Name`，所以找到之后就可以退出函数了。
RFC原话：
>  Note: Earlier versions of this specification permitted multiple names of the same name_type.  In practice, current client       implementations only send one name, and the client cannot necessarily find out which name the server selected.  Multiple       names of the same name_type are therefore now prohibited.
