### ISSUE TITLE
从 TLS handshake中提取 server_name 又发现了两处错误！！！

### ISSUE THREAD

**Issue by 11235yuan** [MiChuancey/Protocol_Restoration#3]
有三处错误，所有错误都是和 len 相关的，拿 pos 和 len 相比较会导致有些包提取不到服务名！

**Comment by CChuancey** [comment]
> 有三处错误，所有错误都是和 len 相关的，拿 pos 和 len 相比较会导致有些包提取不到服务名！

发一下相关pcap包

**Comment by CChuancey** [comment]
> 有三处错误，所有错误都是和 len 相关的，拿 pos 和 len 相比较会导致有些包提取不到服务名！

错误请标明，或提交`Pull request`。

**Comment by CChuancey** [comment]
> 有三处错误，所有错误都是和 len 相关的，拿 pos 和 len 相比较会导致有些包提取不到服务名！

之前的函数逻辑太混乱了，刚参考openssl解析报文的方式，重写了SNI的解析部分，使用最新的代码。
如果还未奏效请另起Issues 提交相关PACP包以及debug信息。

**Comment by 11235yuan** [comment]
您好，感谢您的回复，我再学习学习最新的版本，用数据集测试一下。之前调试的时候的 问题已经在好几天前解决了，不能正确提取的 pcap 包已经被我删除了。待会儿用 OpenHttpsDataset（https://betternet.lhs.loria.fr/datasets/https/index.html） 这个数据集测试一下，我是先用 pkt2flow 提取 tcp 流，然后再用 SNI 部分提取 Server Name；也可以直接用 SNI 部分提取原始PCAP中的Server Name，在和 Wireshark 提取的对比；Wireshark 对验证不合法的 TCP 包不提取 Server Name，但是我发现有些不合法的TCP包中也是能够正确提取到 Server Name 的，可能是包里的TLS handshake部分还是正确的，
